#print
print ('We are learning python')
print ("We are learning python")
print('1', '2', '4', '8', '16')
print()
print('text1')
print()
print('text1')
print()
print("when we need 'this' we use")
print('when we need "this" we use')
print('4')
print('8')
print('15')
print('16')
print('23')
print('42')
print('*')
print('**')
print('***')
print('****')
print('*****')
print('******')
print('*******')